services:
  fast-api:
    image: nachman/fast-api:v0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - shared-net
    env_file:
      - .env
    volumes:
      - ./code:/FastAPI

networks:
  shared-net:
    external: true
    name: shared-bridge
    
